apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: lanchonete
  labels:
    app: order
    environment: production
spec:
  type: ClusterIP
  selector:
    app: order
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
