services:
  wiremock:
    container_name: wiremock
    image: holomekc/wiremock-gui:latest
    ports:
      - "8090:8090"
    volumes:
      - ./__files/:/home/wiremock/__files
      - ./mappings/:/home/wiremock/mappings
    environment:
      WIREMOCK_OPTIONS: "--port=8090"

  database:
    container_name: mongo-server
    image: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=lanchonete
    ports:
      - "27017:27017"

  database-adm-tools:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_URL=mongodb://root:password@mongo-server:27017/
    links:
      - database
    depends_on:
      - database



